jobs:
 - reduce_sectors:
    reduce:
      - {topologies: [hxb], sectors: [b0111001100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0111010100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1101010100000],r: 6,s: 3,d: 1}
    select_integrals:
     select_mandatory_list:
      - {topologies: [hxb], sectors: [b0111001100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0111010100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1101010100000],r: 6,s: 3,d: 1}
    run_initiate: true
    numerical_points: numerics
    run_firefly: true
