jobs:
 - reduce_sectors:
    reduce:
      - {topologies: [hxb], sectors: [b0101010100000],r: 5,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1001010100000],r: 5,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0011011100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0101011100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0101110100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1001011100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1001110100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0011001110000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0011010110000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0101101100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1001101100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0101010110000],r: 6,s: 3,d: 1}
    select_integrals:
     select_mandatory_list:
      - {topologies: [hxb], sectors: [b0101010100000],r: 5,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1001010100000],r: 5,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0011011100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0101011100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0101110100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1001011100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1001110100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0011001110000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0011010110000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0101101100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b1001101100000],r: 6,s: 3,d: 1}
      - {topologies: [hxb], sectors: [b0101010110000],r: 6,s: 3,d: 1}
    run_initiate: true
    numerical_points: numerics
    run_firefly: true
